### ISSUE TITLE
Mapping for ElasticSearch fixtures

### ISSUE THREAD

**Issue by dmatsinger** [zumba/elasticsearchunit#5]
Currently there is no way to map ElasticSearch fixtures.  Without this nested calls/sorts will throw exceptions, searches and sorts may return invalid data, etc.

**Comment by cjsaylor** [comment]
@dmatsingerzumba Is this still valid (especially since #6 was merged)?

**Comment by dmatsinger** [comment]
@cjsaylor This issue can be closed due to #6
